name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow   
  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    
    - name: GitVersion
      uses: docker://gittools/gitversion:5.2.5-linux-ubuntu-16.04-netcoreapp2.1
      with:
        args: /github/workspace /nofetch /output buildserver

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*   
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build ${{ env.GitVersion_SemVer }}
      run: dotnet build --configuration Release --no-restore /p:AssemblyVersion=${{ env.GitVersion_SemVer }} /p:FileVersion=${{ env.GitVersion_SemVer }} /p:InformationalVersion=${{ env.GitVersion_SemVer }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Setup nuget config
      run: sed -i 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' nuget.config
      working-directory: src

    - name: Package
      run: dotnet pack --configuration Release --no-build -p:PackageVersion=${{ env.GitVersion_SemVer}}
    
    #- name: Publish to github
    #  run: dotnet nuget push **/*.nupkg --source github --skip-duplicate --no-symbols true
    #  working-directory: src

    - name: Publish to github
      run: dotnet nuget push SmartThingsNet.${{ env.GitVersion_SemVer}}.nupkg --source "github" --skip-duplicate --no-symbols true
      working-directory: src/bin/Release
      
    - name: Publish to nuget
      run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
      

